### ISSUE TITLE
Create wiring diagram

### ISSUE THREAD

**Issue by SUPScientist** [SUPScientist/smart-coasts-bathy-mapping#4]
Create diagram showing key connections between Boron, FeatherWings, and sensor. 

Sensor also has a power boost chip and a level shifter. We're feeding 3.3 V to a chip that boosts it to 5 V to give the sensor what it needs, but then we pass the 5 V ECHO signal back through the level shifter to get it back to 3.3 V so that it doesn't fry the Boron.

FeatherWing wiring can be simplified since FeatherWings are designed to fit onto Feathers without need for additional wires, but showing communications (e.g., I2C, SPI, UART) blocks and, especially, chip select pins would help.

**Comment by carolinaj6** [comment]
Here is the diagram. ![image](https://github.com/SUPScientist/smart-coasts-bathy-mapping/assets/143202254/fcb8523a-feac-4efe-a9b5-dc76acf4eda8)

**Comment by SUPScientist** [comment]
@carolinaj6, this is great, nice work! A few recommended improvements:

- [x] Change the +3.3V symbol to the simpler rail symbol. Your current symbol suggests a battery there, which isn't exactly true (the one and only battery is plugged into the Boron's Li+ pin).
- [x] The temperature sensor is now a 3-wire, analog sensor. This one: https://learn.adafruit.com/tmp36-temperature-sensor/overview. Please update and show proper analog input on Boron side (A4).
- [x] On the Adalogger Featherwing, all wiring needs to be updated. Power and ground should mimic power and ground to the other devices (i.e., the ground symbol and power rail symbol) and data wires should follow https://learn.adafruit.com/adafruit-adalogger-featherwing/pinouts#sd-and-spi-pins-2933321. The Boron uses its D5 pin for the CS.
- [x] The level shifter has 3.3 V coming in (not 5). 
- [x] Add the power boost chip to show how 5V is created from the 3.3V and then how that 5V is passed to the distance sensor. 
- [x] What you've done to show the "unused" pins makes sense, but maybe add "/reserved" to the label so that readers know that they're not used but nor are they available for other uses. 

I know this may seem like a lot but it will go a long way in communicating your progress to the outside world. Thanks and let me know if you have questions!

**Comment by carolinaj6** [comment]
@SUPScientist Ok. I will get to work on those edits. For the fifth bullet, I'm not sure if I understand. Is the power chip different from the level shifter? Is it another component or an edit I need to make to the level shifter? Thank you!

**Comment by SUPScientist** [comment]
Excellent, thanks. Yes, the power chip is different. It got confusing with the need to boost UP the power to 5V for the distance sensor but then level shift the output back DOWN for the return to the Boron! Indu found this DD0505MD to do the power boost. Thankfully it only has three pins. It takes 3.3V and GND in/out, and sends 5V out. That GND is the same shared GND used across our entire system.

**Comment by carolinaj6** [comment]
@SUPScientist I have made those edits. Here is the updated wire diagram. One last question - should the trig go to voltage in on the level shifter and that gets sent to the boron or should trig from the distance sensor go straight to the boron? And what about for echo? Let me know how I can change that up. Thank you!

**Comment by carolinaj6** [comment]
![image](https://github.com/SUPScientist/smart-coasts-bathy-mapping/assets/143202254/78120d19-3846-4b4f-941a-ba0d2b0655f5)

**Comment by SUPScientist** [comment]
@carolinaj6, this looks great, nice work! Can you submit a Pull Request ("PR") wherein you replace the image currently in the new Wiring folder (https://github.com/SUPScientist/smart-coasts-bathy-mapping/blob/main/Wiring/Wiring-Diagram.jpeg) with this one, at higher resolution if that's possible? This one looks a little blurry, but maybe that's as good as it gets with the free software. I'll close this issue once there's a PR and/or commit to link to. Thanks!

**Comment by SUPScientist** [comment]
Closing with https://github.com/SUPScientist/smart-coasts-bathy-mapping/pull/8. Thanks, @carolinaj6!
